# Generated by Django 5.2.3 on 2025-08-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_blogs_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs_image'),
        ),
    ]
