# Generated by Django 5.2.3 on 2025-08-10 07:00
from django_ckeditor_5.fields import CKEditor5Field
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_blogs_blog_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blog_body',
        ),
        migrations.AddField(
            model_name='blogs',
            name='long_description',
            field=CKEditor5Field('Text', config_name='default', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]

