# Generated by Django 5.2.3 on 2025-08-10 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_remove_blogs_blog_body_blogs_long_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='long_description',
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
