# Generated by Django 5.2.3 on 2025-08-10 07:12

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_remove_blogs_blog_body_blogs_long_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='long_description',
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_body',
            field=CKEditor5Field('Text', config_name='default', default='No content yet.'),
        ),
    ]
