# Generated by Django 5.2.5 on 2025-08-20 11:31

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_alter_blogs_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_body',
            field=CKEditor5Field('Text', config_name='default'),
        ),
    ]
