# Generated by Django 5.2.5 on 2025-08-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0023_alter_feedback_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='Guest', max_length=255),
        ),
    ]
