# Generated by Django 5.2.5 on 2025-08-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0027_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name_plural': 'contctmassage'},
        ),
    ]
