# Generated by Django 5.2.5 on 2025-08-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0029_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGroupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Team', max_length=100)),
                ('image', models.ImageField(upload_to='group_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
