# Generated by Django 5.2.5 on 2025-08-31 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0030_teamgroupimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
    ]
