# Generated by Django 5.2.5 on 2025-08-31 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0032_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='is_feacherd',
            new_name='is_featured',
        ),
    ]
